### ISSUE TITLE
New clone: NoMethodError: undefined method `year' for nil:NilClass

### ISSUE THREAD

**Issue by amypivo** [calagator/calagator#299]
Hey, 

I've just cloned the repo and tried to run setup. When I try to seed the db I get:

       NoMethodError: undefined method `year' for nil:NilClass

Full trace: 
```
    /Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
** SecretsReader - WARNING! Using insecure 'config/secrets.yml.sample' settings, see 'Security' in INSTALL.md
rake aborted!
NoMethodError: undefined method `year' for nil:NilClass
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/values/time_zone.rb:275:in `parse'
/Users/AmyPivo/Projects/calagator/app/models/event.rb:130:in `time_for'
/Users/AmyPivo/Projects/calagator/app/models/event.rb:113:in `start_time='
/Users/AmyPivo/Projects/calagator/app/mixins/decode_html_entities_hack.rb:25:in `block in decode_html_entities'
/Users/AmyPivo/Projects/calagator/app/mixins/decode_html_entities_hack.rb:22:in `each'
/Users/AmyPivo/Projects/calagator/app/mixins/decode_html_entities_hack.rb:22:in `decode_html_entities'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:462:in `_run__2149792940784482683__validate__860138964496062200__callbacks'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_validate_callbacks'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activemodel-3.2.19/lib/active_model/validations.rb:228:in `run_validations!'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activemodel-3.2.19/lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:414:in `_run__2149792940784482683__validation__860138964496062200__callbacks'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_validation_callbacks'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activemodel-3.2.19/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activemodel-3.2.19/lib/active_model/validations.rb:195:in `valid?'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/validations.rb:69:in `valid?'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/validations.rb:77:in `perform_validations'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/validations.rb:56:in `save!'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/transactions.rb:264:in `block in save!'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/transactions.rb:208:in `transaction'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/transactions.rb:264:in `save!'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block (2 levels) in define_list_strategy_method'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `times'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `each'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `map'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block in define_list_strategy_method'
/Users/AmyPivo/Projects/calagator/spec/factories.rb:61:in `block (4 levels) in <top (required)>'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/callback.rb:13:in `instance_exec'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/callback.rb:13:in `run'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/callbacks_observer.rb:11:in `block in update'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/callbacks_observer.rb:10:in `each'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/callbacks_observer.rb:10:in `update'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:20:in `notify'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:13:in `block in result'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block (2 levels) in define_list_strategy_method'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `times'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `each'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `map'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block in define_list_strategy_method'
/Users/AmyPivo/Projects/calagator/db/seeds.rb:13:in `<top (required)>'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/railties-3.2.19/lib/rails/engine.rb:525:in `load_seed'
/Users/AmyPivo/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.19/lib/active_record/railties/databases.rake:347:in `block (2 levels) in <top (required)>'

**Comment by jc00ke** [comment]
Try running with Ruby 2.1.x. We don't support 2.2.x quite yet.

**Comment by amypivo** [comment]
Thanks! I knew it was going to be something easy I missed.

**Comment by amypivo** [comment]
I put in a pull request to help address this issue.

**Comment by jc00ke** [comment]
#300
