### ISSUE TITLE
Flickering tests when running locally

### ISSUE THREAD

**Issue by kerrizor** [calagator/calagator#437]
I'm getting a lot of flickering tests locally, specifically related to capybara and what appear to be timeouts. It's always the same 3 or 4, and they flicker regardless of seed. The Poltergeist one is likely fixable with a timeout increase, as its the flickery-est, but the others are a bit more wondering.

Test suite output below; I ran through installation and README and did a couple installs from scratch but haven't isolated the cause.. is it just me? :)

```
  1) Administrative suite is hidden behind an http basic auth wall Users are not permitted in /venues/duplicates
     Failure/Error: visit path
     Capybara::Poltergeist::TimeoutError:
       Timed out waiting for response to {"name":"visit","args":["http://127.0.0.1:56359/venues/duplicates"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/poltergeist-1.6.0/lib/capybara/poltergeist/web_socket_server.rb:87:in `rescue in send'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/poltergeist-1.6.0/lib/capybara/poltergeist/web_socket_server.rb:83:in `send'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/poltergeist-1.6.0/lib/capybara/poltergeist/server.rb:33:in `send'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:316:in `command'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:31:in `visit'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/admin_auth_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:135:in `block (2 levels) in <top (required)>'
```

```
  1) Administrative suite is hidden behind an http basic auth wall Authenticated users are permitted in /admin
     Failure/Error: expect([200, 304]).to include page.status_code
       expected [200, 304] to include nil
     # ./spec/features/admin_auth_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:135:in `block (2 levels) in <top (required)>'
```

```
  1) Administrative suite is hidden behind an http basic auth wall Users are not permitted in /admin
     Failure/Error: expect(page.status_code).to eq 401

       expected: 401
            got: nil

       (compared using ==)
     # ./spec/features/admin_auth_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:135:in `block (2 levels) in <top (required)>'
```

```
  1) Administrative suite is hidden behind an http basic auth wall Users are not permitted in /events/duplicates
     Failure/Error: expect(page.status_code).to eq 401

       expected: 401
            got: nil

       (compared using ==)
     # ./spec/features/admin_auth_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:135:in `block (2 levels) in <top (required)>'
```

```
  1) import events from a feed A user imports an events from a feed
     Failure/Error: fill_in 'URL', with: 'http://even.ts/feed'
     Capybara::ElementNotFound:
       Unable to find field "URL"
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/node/finders.rb:41:in `block in find'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/node/actions.rb:56:in `fill_in'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
     # /Users/kerrimiller/.rvm/gems/ruby-2.1.6/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/import_events_from_feed_spec.rb:17:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:135:in `block (2 levels) in <top (required)>'
```

**Comment by reidab** [comment]
I've seen occasional flickering on Travis runs as well. I some of those were the Poltergeist timeout issue, but the others may have cropped up as well. It's definitely worth looking into further.

**Comment by aeschright** [comment]
We're no longer using Poltergeist, so I'm going to close this. You can open another ticket if the current tests seem to be doing something similar (but I hope not!)
