### ISSUE TITLE
Running Callagator via docker image: "can't modify frozen String" error

### ISSUE THREAD

**Issue by pc-magas** [calagator/calagator#512]
When I try to run the application *inside* a docker container usinf ruby 2.2.6 I get the following error:

```
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/generators/actions.rb:26:in `gem': can't modify frozen String (RuntimeError)
	from /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb:37:in `block (2 levels) in apply'
	from /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb:36:in `each'
	from /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb:36:in `block in apply'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/generators/actions.rb:57:in `instance_eval'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/generators/actions.rb:57:in `block in gem_group'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/actions.rb:195:in `block in in_root'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/actions.rb:185:in `block in inside'
	from /usr/local/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
	from /usr/local/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/actions.rb:185:in `inside'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/actions.rb:195:in `in_root'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/generators/actions.rb:53:in `gem_group'
	from /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb:33:in `apply'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/actions.rb:224:in `instance_eval'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/actions.rb:224:in `apply'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/generators/app_base.rb:144:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/cli.rb:14:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/railties-4.2.7.1/bin/rails:9:in `<top (required)>'
	from /usr/local/bundle/bin/rails:22:in `load'
	from /usr/local/bundle/bin/rails:22:in `<main>'

```
To produce the error I run:

I used the following commands to setup a docker image for ruby 2.2.6 giving a bash shell access:

```
docker run -ti ruby:2.2.6 bash
```

Afterwards *inside* the docker container I run the following commands as specified on INSTALL.md

```
gem install calagator --pre
```

Afterwards I run:

```
calagator new my_great_calendar
```

And that gave me the error mentioned above.

**Comment by iandees** [comment]
The install instructions say to use Ruby 1.9.3 - 2.1.x, and you're using 2.2.6. Try an older Ruby?

**Comment by iandees** [comment]
Alas, it doesn't work on older ruby and still doesn't work with `ruby:2.2`:

```
$ docker run -it --rm ruby:2.2 bash
# gem install calagator --pre
# calagator new my_great_calendar
...
       apply  /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb
     gemfile    group :development, :test
      append    Gemfile
/usr/local/bundle/gems/railties-4.2.9/lib/rails/generators/actions.rb:26:in `gem': can't modify frozen String (RuntimeError)
	from /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb:37:in `block (2 levels) in apply'
	from /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb:36:in `each'
	from /usr/local/bundle/gems/calagator-1.0.0.rc3/rails_template.rb:36:in `block in apply'
	from /usr/local/bundle/gems/railties-4.2.9/lib/rails/generators/actions.rb:57:in `instance_eval'
...
```

**Comment by DrmCtchr** [comment]
cheezy workaround is to comment out the line (26):
#message << " (#{version})"

This will at least allow you to get the process up and active for testing purposes. You will have to figure out how to mod the file in your container, prior to starting the server.
