### ISSUE TITLE
Unable to create new calagator site

### ISSUE THREAD

**Issue by xrd** [calagator/calagator#658]
I'm following the instructions in the README. I tried with various versions of ruby (via RVM).  I always get some variant of this:

```
$ calagator new calendar
...
/home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/calagator-1.1.0/rails_template.rb:29:in `apply': undefined method `find_by' for Gem::Specification:Class (NoMethodError)
Did you mean?  min_by
...
```

My environment:

```
$ uname -a
Linux pop-os 5.4.0-7634-generic #38~1596560323~20.04~7719dbd-Ubuntu SMP Tue Aug 4 19:12:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
$ gem --version
3.0.9
$ ruby --version
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-linux]
```

Full stack trace:

```
$ calagator new calendar
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/javascripts/application.js
      create  app/assets/stylesheets/application.css
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/views/layouts/application.html.erb
      create  app/assets/images/.keep
      create  app/mailers/.keep
      create  app/models/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/session_store.rb
      create  config/initializers/to_time_preserves_timezone.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
       apply  /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/calagator-1.1.0/rails_template.rb
/home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/calagator-1.1.0/rails_template.rb:29:in `apply': undefined method `find_by' for Gem::Specification:Class (NoMethodError)
Did you mean?  min_by
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/actions.rb:227:in `instance_eval'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/actions.rb:227:in `apply'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/railties-4.2.11.3/lib/rails/generators/app_base.rb:144:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/railties-4.2.11.3/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /home/chrisdawson/.rvm/rubies/ruby-2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/chrisdawson/.rvm/rubies/ruby-2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/railties-4.2.11.3/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/chrisdawson/.rvm/rubies/ruby-2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/chrisdawson/.rvm/rubies/ruby-2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/gems/railties-4.2.11.3/bin/rails:9:in `<top (required)>'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/bin/rails:23:in `load'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/bin/rails:23:in `<main>'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/bin/ruby_executable_hooks:22:in `eval'
	from /home/chrisdawson/.rvm/gems/ruby-2.4.9/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by xrd** [comment]
I'm making a little progress running inside docker. But when I attempted to mount it as an engine:

```
uninitialized constant Calagator::Event::DecodeHtmlEntitiesHack
Extracted source (around line #45):
              
    xss_foliate strip: %i[title description venue_details]

    include DecodeHtmlEntitiesHack

```

**Comment by xrd** [comment]
If I use this `Dockerfile` I get past the "install" but it fails with the above error.

```
FROM ruby:2.5

# RUN mkdir -p /app
# WORKDIR /app
RUN gem install calagator -v 1.1.0
RUN calagator new simple
WORKDIR simple
RUN bundle install
RUN echo "gem 'execjs'" >> Gemfile
RUN echo "gem 'therubyracer'" >> Gemfile
RUN bundle install

RUN apt update
RUN apt install -y emacs

# Delete the sqlite, fix it.
RUN sed '/sqlite3/d' Gemfile > Gemfile.tmp
RUN rm Gemfile
RUN mv Gemfile.tmp Gemfile
RUN echo 'gem "sqlite3", "~> 1.3", "< 1.4"' >> Gemfile

RUN echo 'gem "calagator", "1.1.0"' >> Gemfile
# RUN echo 'gem "sqlite3"' >> Gemfile
RUN bundle update
RUN bundle install

# RUN bundle exec rake db:migrate
RUN ./bin/rails g calagator:install

CMD ./bin/rails server --binding 0.0.0.0 --port 3000
```
